// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOz4NZtxU0ARd9Tcqd2jG8glDuvfIWwtY',
    appId: '1:759518092175:web:6fb2f56f8fd3bfb50549fa',
    messagingSenderId: '759518092175',
    projectId: 'movieapp-dba62',
    authDomain: 'movieapp-dba62.firebaseapp.com',
    storageBucket: 'movieapp-dba62.firebasestorage.app',
    measurementId: 'G-EBFP0JWWSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQf5TjjxvGrcH7SvsXgjOMF_3YBhOhcPw',
    appId: '1:759518092175:android:ebf3558aedd5c8530549fa',
    messagingSenderId: '759518092175',
    projectId: 'movieapp-dba62',
    storageBucket: 'movieapp-dba62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHa3mH13PBmNSEiPjUk6Fyt681vIGC1e4',
    appId: '1:759518092175:ios:9d8369eeb21199e90549fa',
    messagingSenderId: '759518092175',
    projectId: 'movieapp-dba62',
    storageBucket: 'movieapp-dba62.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHa3mH13PBmNSEiPjUk6Fyt681vIGC1e4',
    appId: '1:759518092175:ios:9d8369eeb21199e90549fa',
    messagingSenderId: '759518092175',
    projectId: 'movieapp-dba62',
    storageBucket: 'movieapp-dba62.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOz4NZtxU0ARd9Tcqd2jG8glDuvfIWwtY',
    appId: '1:759518092175:web:27632ef2f29986080549fa',
    messagingSenderId: '759518092175',
    projectId: 'movieapp-dba62',
    authDomain: 'movieapp-dba62.firebaseapp.com',
    storageBucket: 'movieapp-dba62.firebasestorage.app',
    measurementId: 'G-8H9X40G8PP',
  );

}